"use client";
import { useState } from "react";
import { AGENT_IDS, AGENT_META } from "@/lib/config/envelopes";
import { useApp } from "@/lib/store/store";
import { Panel } from "./ui";

export function AgentLog() {
  const agents = useApp((s) => s.agents); const decisions = useApp((s) => s.decisions); const tick = useApp((s) => s.clock.tick);
  const [selectedId, setSelectedId] = useState(AGENT_IDS[0]); const selected = agents[selectedId]; const meta = AGENT_META[selectedId];
  const recent = decisions.filter((d) => d.agentId === selectedId).slice(-6).reverse();
  return <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(300px,420px)]"><Panel title="Agent log" right={<span className="font-mono text-[10px] text-tower-dim">{AGENT_IDS.length} agents · cycle {tick}</span>} bodyClass="grid gap-2 p-3 sm:grid-cols-2 xl:grid-cols-3">{AGENT_IDS.map((id) => { const a = agents[id]; const m = AGENT_META[id]; const active = id === selectedId; const working = tick - (a.lastTick ?? -99) <= 1; return <button key={id} onClick={() => setSelectedId(id)} className={`rounded-sm border p-3 text-left transition ${active ? "border-tower-cyan bg-tower-cyan/10" : "border-tower-line bg-[#0b141d] hover:border-tower-dim"}`}><div className="flex items-center justify-between gap-2"><span className="flex items-center gap-2 font-mono text-xs font-semibold" style={{ color: m.color }}><i className={`h-1.5 w-1.5 rounded-full ${working ? "bg-tower-green" : a.status === "blocked" ? "bg-tower-red" : "bg-[#2a3847]"}`} />{m.name}</span><span className="font-mono text-[10px] text-tower-dim">{working ? "working" : "idle"}</span></div><div className="mt-2 truncate text-[11px] text-tower-dim">{a.lastAction ?? "Waiting for first task"}</div><div className="mt-3 flex justify-between font-mono text-[10px] text-tower-dim"><span>{a.decisions.toLocaleString("en-IN")} decisions</span><span>{Math.round(Math.min(1, a.envelopeUtil) * 100)}% envelope</span></div></button>; })}</Panel><Panel title={`${meta.name} · working view`} right={<span className="font-mono text-[10px] text-tower-cyan">selected</span>}><div className="space-y-3"><div className="rounded-sm border border-tower-cyan/20 bg-tower-cyan/5 p-3"><div className="font-mono text-[10px] uppercase tracking-wider text-tower-dim">Current activity</div><div className="mt-1 text-sm text-white">{selected.lastAction ?? "Waiting for the engine to assign work"}</div><div className="mt-2 font-mono text-[10px] text-tower-dim">Status: {selected.status} · last cycle: {selected.lastTick ?? "—"}</div></div><div className="grid grid-cols-3 gap-2 font-mono text-center text-[10px]"><div className="rounded-sm bg-[#0b141d] p-2"><b className="block text-sm text-white">{selected.decisions}</b>decisions</div><div className="rounded-sm bg-[#0b141d] p-2"><b className="block text-sm text-white">{selected.proposals}</b>proposals</div><div className="rounded-sm bg-[#0b141d] p-2"><b className="block text-sm text-tower-amber">{selected.escalations}</b>escalations</div></div><div><div className="mb-2 font-mono text-[10px] uppercase tracking-wider text-tower-dim">Recent decisions</div>{recent.length ? <div className="space-y-2">{recent.map((d) => <div key={d.id} className="border-l border-tower-cyan/40 pl-2"><div className="text-xs text-white">{d.title}</div><div className="mt-0.5 line-clamp-2 text-[10px] text-tower-dim">{d.summary || d.reasoning}</div></div>)}</div> : <div className="font-mono text-xs text-tower-dim">No decisions recorded yet.</div>}</div></div></Panel></div>;
}
