"use client";
import { AGENT_IDS, AGENT_META } from "@/lib/config/envelopes";
import { useApp } from "@/lib/store/store";
import type { Order, OrderStatus } from "@/lib/types";

const role: Record<(typeof AGENT_IDS)[number], string> = {
  demand: "Checks live demand and product velocity.", pricing: "Protects price and margin.", inventory: "Reserves stock and checks availability.", placement: "Balances stock between warehouses.", procurement: "Plans replenishment if stock is short.", fulfilment: "Selects the warehouse that can fulfil this order.", courier: "Chooses the best courier and delivery route.", returns: "Assesses return and COD/RTO risk.", risk: "Watches for service, supplier, and fraud risks.", finance: "Checks cash, payment, and settlement implications.",
};

export function OrderAgentFlow3D({ order }: { order: Order }) {
  const agents = useApp((s) => s.agents); const decisions = useApp((s) => s.decisions); const tick = useApp((s) => s.clock.tick); const catalog = useApp((s) => s.catalog); const inventory = useApp((s) => s.inventory); const forecasts = useApp((s) => s.forecasts); const settlements = useApp((s) => s.settlements);
  const orderId = order.id; const status: OrderStatus = order.status;
  return <section className="order-flow-3d border-t border-tower-line bg-[#070d13] p-4"><div className="flex flex-wrap items-baseline justify-between gap-2"><div><div className="font-mono text-[10px] uppercase tracking-[.2em] text-tower-dim">Live agent journey</div><h3 className="mt-1 text-sm font-semibold text-white">How the network is handling {orderId}</h3></div><span className="rounded-full border border-tower-cyan/30 bg-tower-cyan/10 px-2 py-1 font-mono text-[10px] text-tower-cyan">{status.replace("_", " ")}</span></div><p className="mt-2 text-xs text-tower-dim">Hover an agent card to see its responsibility and current order-specific evidence.</p><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{AGENT_IDS.map((id, index) => { const agent = agents[id]; const meta = AGENT_META[id]; const matching = decisions.slice().reverse().find((d) => d.agentId === id && `${d.summary} ${d.reasoning}`.includes(orderId)); const working = tick - (agent.lastTick ?? -99) <= 1; const state = matching ? "decision made" : working ? "working now" : "live check"; const activity = matching?.summary || orderActivity(id, order, catalog, inventory, forecasts, settlements); return <div key={id} className="order-agent-card group relative" style={{ animationDelay: `${index * 90}ms` }}><div className={`order-agent-face h-full rounded-lg border p-3 ${working ? "border-tower-cyan/70 bg-tower-cyan/[.08]" : "border-tower-line bg-[#0c151e]"}`}><div className="flex items-center justify-between gap-2"><span className="h-2.5 w-2.5 rounded-full" style={{ background: meta.color, boxShadow: working ? `0 0 12px ${meta.color}` : "none" }} /><span className="font-mono text-[9px] uppercase tracking-wider text-tower-dim">{state}</span></div><div className="mt-3 font-mono text-sm font-semibold" style={{ color: meta.color }}>{meta.name}</div><div className="mt-1 line-clamp-2 text-[11px] leading-relaxed text-tower-dim">{activity}</div><div className="mt-3 h-1 overflow-hidden rounded-full bg-[#17232e]"><div className="h-full rounded-full transition-all duration-700" style={{ width: `${Math.max(8, Math.min(100, agent.envelopeUtil * 100))}%`, background: meta.color }} /></div></div><div className="order-agent-popup"><div className="font-mono text-xs font-semibold" style={{ color: meta.color }}>{meta.name}</div><p className="mt-1">{role[id]}</p><div className="mt-2 border-t border-white/10 pt-2 text-white">{activity}</div></div></div>; })}</div><div className="mt-5 flex flex-wrap items-center gap-2 font-mono text-[10px] text-tower-dim"><span className="text-tower-cyan">● active/working</span><span>→</span><span>hover any card for a decision popup</span><span>→</span><span>live cycle {tick}</span></div></section>;
}

function orderActivity(id: (typeof AGENT_IDS)[number], order: Order, catalog: ReturnType<typeof useApp.getState>["catalog"], inventory: ReturnType<typeof useApp.getState>["inventory"], forecasts: ReturnType<typeof useApp.getState>["forecasts"], settlements: ReturnType<typeof useApp.getState>["settlements"]) {
  const first = order.lines[0]; const product = first ? catalog.find((p) => p.sku === first.sku) : undefined; const onHand = first ? Object.values(inventory[first.sku] ?? {}).reduce((a, b) => a + b, 0) : 0; const forecast = first ? forecasts[first.sku] : undefined;
  if (id === "demand") return product ? `${product.name}: forecast ${forecast?.daily?.toFixed(1) ?? "pending"}/day · velocity ${forecast?.velocityMult?.toFixed(1) ?? "1.0"}×.` : "Waiting for line-item data.";
  if (id === "pricing") return product ? `${product.name}: ${order.region} price ₹${product.zonePrice[order.region]} · margin guardrail active.` : "Price is being validated.";
  if (id === "inventory") return `${onHand} units available across the network for this order's SKU${order.lines.length > 1 ? "s" : ""}.`;
  if (id === "placement") return order.warehouseId ? `Stock positioned at ${order.warehouseId}; regional balance remains under review.` : "No node reserved yet; evaluating stock geography.";
  if (id === "procurement") return order.status === "backordered" ? "Order is short on stock; replenishment demand is being checked." : "No replenishment is required for this order right now.";
  if (id === "fulfilment") return order.warehouseId ? `Fulfilled from ${order.warehouseId}.` : order.status === "backordered" ? "No warehouse can currently fill the order." : "Comparing warehouse stock, cost, and SLA.";
  if (id === "courier") return order.courierId ? `Assigned ${order.courierId}; promise ${order.promisedDays ?? "pending"} day(s).` : "Comparing courier cost, SLA, and RTO exposure.";
  if (id === "returns") return order.rto ? `COD/RTO score ${Math.round(order.rto.p * 100)}% · ${order.rtoMeasure === "ivr_confirm" ? "IVR confirmation applied" : "standard return controls"}.` : "Return risk will be evaluated after shipment.";
  if (id === "risk") return order.status === "backordered" ? "Service exception detected: backorder is being monitored." : order.status === "rto" ? "RTO outcome recorded; route performance will be recalibrated." : "No order-level exception currently detected.";
  const settlement = settlements.find((s) => s.orderIds.includes(order.id)); return settlement ? `Settlement ${settlement.id} is ${settlement.status}; value is included in reconciliation.` : `Cash and settlement exposure tracked for ₹${order.value.toLocaleString("en-IN")} order value.`;
}
